channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=24.0
- pip:
  - mlflow==2.9.2
  - cffi==1.15.1
  - cloudpickle==3.0.0
  - colorama==0.4.3
  - distribute==0.7.3
  - importlib-metadata==6.0.0
  - ipywidgets==7.7.5
  - matplotlib==3.7.1
  - numpy==1.23.5
  - packaging==23.2
  - pandas==2.0.3
  - pathlib==1.0.1
  - scikit-learn==1.2.1
  - scipy==1.10.1
  - seaborn==0.12.2
  - typing==3.7.4.3
name: mlflow-env
